import "server-only";

import { z } from "zod";

import drugMap from "@/fixtures/nhs-drug-map.json";

import { env } from "../env";
import { nhsIndexKey, nhsMedicineKey } from "../store/keys";
import { redis } from "../store/redis";

// Medicine safety information from NHS.uk's medicines A-Z, which publishes it
// as schema.org JSON-LD under the Open Government Licence v3.0.
//
// The licence obliges us to attribute every separate appearance of this content
// and to keep a visible boundary between the NHS's words and ours, so a result
// always carries where it came from and when — see `Provenance`. Unmodified
// English refreshed inside seven days may name the NHS; a translation or a
// stale copy may not.

const NHS_MEDICINES = "https://www.nhs.uk/medicines/";
const CACHE_TTL_SECONDS = 24 * 60 * 60;

export type UrgentBlock = { aspect: string; headline: string; text: string };

export type Provenance = {
  origin: "nhs" | "cache" | "seed";
  // ISO date the content was read from NHS.uk. Drives the "as at" the licence
  // requires on anything not refreshed.
  retrievedOn: string;
};

// Four states, never a bare null. "The page exists but carries no urgent
// block" and "this drug is not on the A-Z at all" mean opposite things to a
// patient, and "we could not reach NHS.uk" must never be shown as either.
export type DrugGuidance =
  | {
      kind: "found";
      slug: string;
      match: "exact" | "partial";
      urgent: UrgentBlock[];
      provenance: Provenance;
    }
  | { kind: "no-urgent-guidance"; slug: string; provenance: Provenance }
  | { kind: "absent" }
  | { kind: "unavailable"; detail: string };

const SeedEntry = z.object({
  normalised: z.string(),
  slug: z.string().nullable(),
  aliasKind: z.enum(["exact", "partial", "absent"]),
  state: z.enum(["found", "no-urgent-guidance", "absent", "unavailable"]),
  urgent: z
    .array(
      z.object({ aspect: z.string(), headline: z.string(), text: z.string() }),
    )
    .nullable(),
});

const SeedMap = z.object({
  generated: z.iso.date(),
  drugs: z.array(SeedEntry),
});

// Parsed once. The file is regenerated by a script rather than hand-edited, so
// a bad regeneration should fail here and not three layers down.
const seed = SeedMap.parse(drugMap);

const seedByName = new Map(
  seed.drugs.map((entry) => [entry.normalised, entry]),
);

export async function lookupDrug(
  normalisedName: string,
): Promise<DrugGuidance> {
  const name = normalisedName.trim().toLowerCase();
  const seeded = seedByName.get(name);

  // Demo mode makes no network call at all. The committed map is licensed for
  // this precisely because a real NHS.uk fetch generated it.
  if (env.NEXT_PUBLIC_PORTICO_MODE === "demo") {
    return seeded === undefined
      ? { kind: "absent" }
      : fromSeed(seeded, seed.generated);
  }

  const resolved = await resolveSlug(name, seeded);
  if (resolved === null) return { kind: "absent" };

  const cached = await readCache(resolved.slug);
  if (cached !== null) {
    return shape(resolved, cached.urgent, {
      origin: "cache",
      retrievedOn: cached.retrievedOn,
    });
  }

  const live = await fetchGuidance(resolved.slug);
  switch (live.kind) {
    case "page":
      await writeCache(resolved.slug, live.urgent, live.retrievedOn);
      return shape(resolved, live.urgent, {
        origin: "nhs",
        retrievedOn: live.retrievedOn,
      });
    case "missing":
      return { kind: "absent" };
    case "failed":
      // Last resort, and labelled as one — never dressed up as a live NHS
      // answer, and never downgraded to "not listed", which would tell a
      // patient their drug has no guidance when it does.
      return seeded === undefined
        ? { kind: "unavailable", detail: live.detail }
        : fromSeed(seeded, seed.generated);
  }
}

type Resolved = { slug: string; match: "exact" | "partial" };

function shape(
  resolved: Resolved,
  urgent: UrgentBlock[],
  provenance: Provenance,
): DrugGuidance {
  return urgent.length === 0
    ? { kind: "no-urgent-guidance", slug: resolved.slug, provenance }
    : {
        kind: "found",
        slug: resolved.slug,
        match: resolved.match,
        urgent,
        provenance,
      };
}

function fromSeed(
  entry: z.infer<typeof SeedEntry>,
  retrievedOn: string,
): DrugGuidance {
  if (entry.slug === null) return { kind: "absent" };
  return shape(
    {
      slug: entry.slug,
      match: entry.aliasKind === "partial" ? "partial" : "exact",
    },
    entry.urgent ?? [],
    { origin: "seed", retrievedOn },
  );
}

// The committed map is the alias layer: a naive name-to-slug fails on nine of
// the corpus's twenty-five drugs. Anything it does not know falls back to the
// live A-Z index.
async function resolveSlug(
  name: string,
  seeded: z.infer<typeof SeedEntry> | undefined,
): Promise<Resolved | null> {
  if (seeded !== undefined) {
    return seeded.slug === null
      ? null
      : {
          slug: seeded.slug,
          match: seeded.aliasKind === "partial" ? "partial" : "exact",
        };
  }

  const slugs = await readIndex();
  const hyphenated = name.replace(/\s+/g, "-");
  if (slugs.includes(hyphenated)) return { slug: hyphenated, match: "exact" };

  // Every patient in scope is an adult, and the A-Z splits several common
  // drugs that way.
  const adult = `${hyphenated}-for-adults`;
  if (slugs.includes(adult)) return { slug: adult, match: "exact" };

  // A single suffixed variant is unambiguous ("salbutamol" -> the inhaler).
  // More than one is a guess, and a guess about a medicine is not worth making.
  const variants = slugs.filter((slug) => slug.startsWith(`${hyphenated}-`));
  return variants.length === 1 && variants[0] !== undefined
    ? { slug: variants[0], match: "exact" }
    : null;
}

const CachedGuidance = z.object({
  urgent: z.array(
    z.object({ aspect: z.string(), headline: z.string(), text: z.string() }),
  ),
  retrievedOn: z.iso.date(),
});

async function readCache(slug: string) {
  const stored = await redis().get<unknown>(nhsMedicineKey(slug));
  return stored === null ? null : CachedGuidance.parse(stored);
}

async function writeCache(
  slug: string,
  urgent: UrgentBlock[],
  retrievedOn: string,
) {
  await redis().set(
    nhsMedicineKey(slug),
    { urgent, retrievedOn },
    { ex: CACHE_TTL_SECONDS },
  );
}

async function readIndex(): Promise<string[]> {
  const stored = await redis().get<unknown>(nhsIndexKey());
  if (stored !== null) return z.array(z.string()).parse(stored);

  const response = await fetch(NHS_MEDICINES, { cache: "no-store" });
  if (!response.ok) {
    throw new Error(`NHS medicines index returned ${response.status}`);
  }
  const slugs = [
    ...new Set(
      [
        ...(await response.text()).matchAll(
          /href="\/medicines\/([a-z0-9-]+)\/"/g,
        ),
      ]
        .map((match) => match[1])
        .filter((slug): slug is string => slug !== undefined),
    ),
  ];
  await redis().set(nhsIndexKey(), slugs, { ex: CACHE_TTL_SECONDS });
  return slugs;
}

type FetchOutcome =
  | { kind: "page"; urgent: UrgentBlock[]; retrievedOn: string }
  | { kind: "missing" }
  | { kind: "failed"; detail: string };

async function fetchGuidance(slug: string): Promise<FetchOutcome> {
  let response: Response;
  try {
    response = await fetch(`${NHS_MEDICINES}${slug}/`, { cache: "no-store" });
  } catch (error) {
    return {
      kind: "failed",
      detail: error instanceof Error ? error.message : String(error),
    };
  }
  if (response.status === 404) return { kind: "missing" };
  if (!response.ok) {
    return { kind: "failed", detail: `NHS.uk returned ${response.status}` };
  }
  return {
    kind: "page",
    urgent: urgentBlocks(await response.text()),
    retrievedOn: new Date().toISOString().slice(0, 10),
  };
}

const LdJson = z.object({
  hasPart: z
    .array(
      z.object({
        hasHealthAspect: z.string().nullish(),
        hasPart: z
          .array(
            z.object({
              identifier: z.string().nullish(),
              headline: z.string().nullish(),
              text: z.string().nullish(),
            }),
          )
          .nullish(),
      }),
    )
    .nullish(),
});

function urgentBlocks(html: string): UrgentBlock[] {
  const script = html.match(
    /<script[^>]*type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/,
  )?.[1];
  if (script === undefined) return [];

  const document = LdJson.safeParse(JSON.parse(script));
  if (!document.success) return [];

  const blocks: UrgentBlock[] = [];
  // The urgent blocks are one level deeper than the health aspects:
  // hasPart[] (HealthTopicContent) -> hasPart[] (WebPageElement). Scanning only
  // the top level finds none, on every drug. And the overdose warning lives
  // under the usage aspect, not side-effects, so every aspect is scanned.
  for (const aspect of document.data.hasPart ?? []) {
    for (const element of aspect.hasPart ?? []) {
      if (element.identifier !== "urgent") continue;
      blocks.push({
        aspect: (aspect.hasHealthAspect ?? "").split("/").at(-1) ?? "",
        headline: element.headline ?? "",
        text: plainText(element.text ?? ""),
      });
    }
  }
  return blocks;
}

// The JSON-LD carries HTML. The text is shown to a patient as the NHS's own
// words, so tags come out and nothing else changes.
function plainText(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}
